remove_definitions(-D_CRT_SECURE_NO_WARNINGS)

if(CMAKE_C_FLAGS MATCHES "--coverage")
    set(CRF_DEMO_HAD_COVERAGE TRUE)
    string(REPLACE "--coverage" "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
    string(REPLACE "-fprofile-arcs" "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
    string(REPLACE "-ftest-coverage" "" CMAKE_C_FLAGS "${CMAKE_C_FLAGS}")
endif()
if(CMAKE_EXE_LINKER_FLAGS MATCHES "--coverage")
    string(REPLACE "--coverage" "" CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}")
endif()

add_subdirectory(app_node_style)
add_subdirectory(app_threaded)
if(NOT EMSCRIPTEN AND NOT CMAKE_SYSTEM_NAME STREQUAL "DOS")
    add_subdirectory(app_multi_process)
endif()
add_subdirectory(app_https_server)
add_subdirectory(notes)
add_subdirectory(app_template_engine)
if(NOT EMSCRIPTEN AND NOT CMAKE_SYSTEM_NAME STREQUAL "DOS")
    add_subdirectory(oauth2)
endif()
add_subdirectory(app_openapi)
add_subdirectory(app_websockets)
add_subdirectory(app_server_sent_events_sse)
add_subdirectory(app_graphql_api)

add_subdirectory(app_http23)
add_subdirectory(app_jwt_json_w)

add_subdirectory(app_full_multi)

if(C_REST_ENABLE_HOT_RELOADING_AUTO_RESTART AND NOT EMSCRIPTEN)
  add_subdirectory(app_hot_reload)
endif()
